#!/bin/bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

logo_sonda_script() {
echo -e "${LB}    SONDA v$(cat $VERSION_FILE 2>/dev/null || echo "unknown")"  | lolcat # This is a fast and lightweight system information. For a more detailed information use -s (system) and -n (network). Type -h to view the complete list of commands."
echo -e ""
echo -e "[i] This is a quick and lightweight system information. "
echo -e "    For more detailed data, use the options '-s' for system information and '-n' for network details. "
echo -e "    Type '-h' to see the full list of available commands."
}

logo_sonda_sysnet() {
bash $ASSETS/art/sonda_sysnet_1 | lolcat
}


# logo_sonda_sysnet_isom4() {
#   echo -e """

#   """ | lolcat
# }

# Generate a random number between 0 and 3
# random_choice=$(( RANDOM % 4 ))

# # Choose one of the 4 variables based on the random number
# case $random_choice in
#     0)
#         source $ASSETS/art/isometric1.sh | lolcat
#         ;;
#     1)
#         source $ASSETS/art/isometric2.sh | lolcat
#         ;;
#     2)
#         source $ASSETS/art/isometric3.sh | lolcat
#         ;;
#     3)
#         source $ASSETS/art/isometric4.sh | lolcat
#         ;;
# esac
